-- KingOfSecretSociety_zh_CN
-- Author: Konomi
-- DateCreated: 7/31/2022 13:25:53
--------------------------------------------------------------

INSERT INTO LocalizedText 
		(Language,		Tag,																Text)
VALUES	('zh_Hans_CN',	'LOC_SECRETSOCIETY_KNM_KING_OF_SECRET_SOCIETY_NAME',				'秘密结社之王'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_KNM_KING_OF_SECRET_SOCIETY_DESCRIPTION',			'“秘密结社之王”的成员们曾经属于其他多个结社，现在他们想成为包罗一切的“王”。但人的精力终究是有限的，即使集众人之力也难以尽善尽美。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_KNM_KING_OF_SECRET_SOCIETY_DISCOVERY',			'“结社，无上神秘权力的个人联结，在我的世界里，关于它们的故事显得荒谬和多余，但在这里，他们的存在让它实现了。”你阅读着突兀出现在宫殿中的书籍，眉头跳了一下。“而在疯狂的世界里，为什么，我们不能欺骗神明?”你颤抖着翻开下一页，方尖碑在嚎叫，地脉在闪耀，城堡流出血腥，帷幕窥视一切——所有的神秘，亵渎地环拥着，一个人类。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_KNM_KING_OF_SECRET_SOCIETY_MEMBERSHIP',			'你感到你在一个灰蒙的大厅中落座。“欢迎你，新的同胞。”厅中的人们仿佛在歌唱。他们样貌各异，在外人看来已投身不同的结社，但此刻他们却坐在一起，甚至在互相演示各自的神秘。[NEWLINE]“我们窃取，”[NEWLINE]“我们探寻，”[NEWLINE]“我们夺下冠冕。”[NEWLINE]你的灵魂已回到现实，面前的书籍上，浮现出燃烧的信条。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_1_NAME',				'初窃火种'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_2_NAME',				'星火渐燃'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_3_NAME',				'窥视权柄'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_4_NAME',				'合秘之书'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_1_DESCRIPTION',		'研究“法典”市政后，+1通用槽位，解锁其他结社的一级效果政策卡。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_2_DESCRIPTION',		'在中世纪解锁。+1通用槽位，解锁其他结社的二级效果政策卡。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_3_DESCRIPTION',		'在工业时代解锁。+1通用槽位，解锁其他结社的三级效果政策卡。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_4_DESCRIPTION',		'在原子能时代解锁。+1通用槽位，解锁其他结社的四级效果政策卡。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_OWLS_OF_MINERVA_1_DESCRIPTION',					'通往城邦的每条 [ICON_TradeRoute] 贸易路线将为此处提供1名 [ICON_Envoy] 使者。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_OWLS_OF_MINERVA_2_DESCRIPTION',					'允许建造“银行”的强力替代品：“镀金宝库”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_OWLS_OF_MINERVA_3_DESCRIPTION',					'+2间谍容量。您的间谍处于本方城市的领土中时，城市每回合+4忠诚度、+1 [ICON_Amenities] 宜居度。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_OWLS_OF_MINERVA_4_DESCRIPTION',					'每回合获得等同于国库3%的 [ICON_Gold] 金币。攻击性间谍任务成功后，获得目标城市在此回合获得的 [ICON_Science] [ICON_Culture] [ICON_Gold] [ICON_Faith] 的一半。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HERMETIC_ORDER_1_DESCRIPTION',						'在地图上永久显示“地脉”资源。此卡取下后将自动销毁。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HERMETIC_ORDER_2_DESCRIPTION',						'允许建造“大学”的强力替代品：“炼金术会所”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HERMETIC_ORDER_3_DESCRIPTION',						'每获得一名 [ICON_GreatPerson] 伟人，地脉便永久获得等同于此 [ICON_GreatPerson] 伟人区域类型的+1产出。此卡取下后将自动销毁。（[ICON_GreatAdmiral] 海军统帅和 [ICON_GreatGeneral] 大将军获得+1 [ICON_Science] 科技值。）'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HERMETIC_ORDER_4_DESCRIPTION',						'解锁“秘术研究”项目。项目在进行时将提供 [ICON_GOLD] 金币，完成时根据城市中的地脉数量提供 [ICON_GreatPerson] 伟人点数和 [ICON_SCIENCE] 科技值。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_VOIDSINGERS_1_DESCRIPTION',						'允许建造“纪念碑”的强力替代品：“旧神方尖碑”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_VOIDSINGERS_2_DESCRIPTION',						'城市每回合获得等同于其每回合所获 [ICON_Faith] 信仰值20%的 [ICON_Gold] 金币、[ICON_Science] 科技值和 [ICON_Culture] 文化值。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_VOIDSINGERS_3_DESCRIPTION',						'解锁单位“邪教徒”。此单位可用 [ICON_Faith] 信仰值购买，可消耗次数来降低外国城市的忠诚度，并生成 [ICON_GreatWork_Relic] 虚空遗物。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_VOIDSINGERS_4_DESCRIPTION',						'解锁“黑暗召唤”。此城市项目在进行时可提供大量 [ICON_Faith] 信仰值，完成后可提升邪教徒造成的忠诚度损失。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SANGUINE_PACT_1_DESCRIPTION',						'[ICON_Capital] 首都出现1个吸血鬼单位。此卡取下后将自动销毁。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SANGUINE_PACT_2_DESCRIPTION',						'[ICON_Capital] 首都出现1个吸血鬼单位，吸血鬼的劳动力永久+2。此卡取下后将自动销毁。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SANGUINE_PACT_3_DESCRIPTION',						'首次采用该政策时 [ICON_Capital] 首都出现1个吸血鬼单位、吸血鬼的劳动力永久+1。吸血鬼能恐吓相邻的敌方单位使其 [ICON_Strength] 战斗力-5，掠夺仅消耗1点 [ICON_Movement] 移动力。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SANGUINE_PACT_4_DESCRIPTION',						'首次采用该政策时 [ICON_Capital] 首都出现1个吸血鬼单位、吸血鬼的劳动力永久+1。吸血鬼城堡1单元格范围中的单位能瞬移至帝国其中一座吸血鬼城堡附近的任意单元格。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INNSMOUTH_1_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“深潜者”单位。允许建造“纪念碑”的强力替代品：“达贡祭坛”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INNSMOUTH_2_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“深潜者”单位。水域单元格+1 [ICON_Gold] 金币、[ICON_Food] 食物、[ICON_Production] 生产力，购买所消耗的 [ICON_Gold] 金币减少30%。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INNSMOUTH_3_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“深潜者”单位。允许建造改良“诡秘漩涡”，水域单元格+2 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INNSMOUTH_4_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“深潜者”单位。解锁“深海幽鸣”城市项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_OTO_1_DESCRIPTION',						'所有单位忽视河流和两栖攻击减益，所有单位 [ICON_Movement] 移动力+1。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_OTO_2_DESCRIPTION',						'拥有港口的城市+30% [ICON_Production] 生产力，建造港口内建筑+50% [ICON_Production] 生产力，海运单位 [ICON_Movement] 移动力+2。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_OTO_3_DESCRIPTION',						'对每个文明获得3级外交能见度。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_OTO_4_DESCRIPTION',						'解锁特殊项目“梦登星宫”，每回合可提供大量 [ICON_Faith] 信仰值并在完成时为所有单位提供一级晋升的城市项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_KAS_1_DESCRIPTION',						'城市中每个特色区域+2 [ICON_Culture] 文化。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_KAS_2_DESCRIPTION',						'拥有剧院广场的城市+15% [ICON_Science] 科技。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_KAS_3_DESCRIPTION',						'赞助 [ICON_GreatPerson] 伟人消耗的 [ICON_Faith] 信仰和 [ICON_Gold] 金币-15%，每位已获得的 [ICON_GreatPerson] 伟人为您的文明+1% [ICON_Science] 科技，+2% [ICON_Culture] 文化。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HOKUSAI_KAS_4_DESCRIPTION',						'解锁特殊项目“如至青原”，每回合可提供大量 [ICON_Culture] 文化值并在完成时提供1个免费市政的城市项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SOLOMON_1_DESCRIPTION',							'每回合+1 [ICON_GreatProphet] 大预言家点数与 [ICON_GreatGeneral] 大将军点数，所有使徒永久获得“演说者”[ICON_Promotion] 强化。每座拥有神社的城市，若其尚未拥有市场或灯塔，则+1 [ICON_TradeRoute] 贸易路线容量。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SOLOMON_2_DESCRIPTION',							'允许建造寺庙的强力替代品“所罗门神殿”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SOLOMON_3_DESCRIPTION',							'政体中每个军事政策槽位提供+5% [ICON_Faith] 信仰值、+5% [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_SOLOMON_4_DESCRIPTION',							'所有陆地战斗单位初始拥有一次免费 [ICON_Promotion] 强化，所有使徒永久获得“劝导者”[ICON_Promotion] 强化，所创立的 [ICON_Religion] 宗教满信条后可免费增加1个信条。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_EMISSARIES_1_DESCRIPTION',							'建造奇观时+15% [ICON_Production] 生产力。相邻奇观的学院建成时获得一个当前时代的随机 [ICON_TechBoosted] 尤里卡。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_EMISSARIES_2_DESCRIPTION',							'所有城市每2 [ICON_Citizen] 人口即可建造新区域，而非3 [ICON_Citizen] 人口。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_EMISSARIES_3_DESCRIPTION',							'允许建造强力的工业区建筑，超铀发电厂。需要消耗 [ICON_RESOURCE_JGP_ELERIUM] 超铀，一种由研究实验室生产的特色战略资源。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_EMISSARIES_4_DESCRIPTION',							'为太空竞赛项目+20% [ICON_Production] 生产力。解锁宇航中心特色项目“出使银河”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BRIGAND_COURT_1_DESCRIPTION',						'清除蛮族营寨后永久+1 [ICON_TradeRoute] 贸易路线。解锁“幻影旗舰”单位，该单位只能同时拥有一艘。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BRIGAND_COURT_2_DESCRIPTION',						'允许建造“灯塔”的强力替代品：亡命徒港湾。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BRIGAND_COURT_3_DESCRIPTION',						'所有海军单位获得海岸掠夺的能力。所有单位掠夺改良和区域将获得双倍收益。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BRIGAND_COURT_4_DESCRIPTION',						'在地图上永久显示 [ICON_RESOURCE_JGP_TREASURE_TROVE] 无主财宝资源，收获后将获得大量 [ICON_Gold] 金币。此卡取下后将自动销毁。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HARMONISTS_1_DESCRIPTION',							'在地图上永久显示“地脉”资源。城市每有一座已解锁但未建造的专业化区域，地脉单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HARMONISTS_2_DESCRIPTION',							'保护区和建筑+2 [ICON_Housing] 住房、+10%城市发展速度。城市每有一座已解锁但未建造的专业化区域，相邻保护区的单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HARMONISTS_3_DESCRIPTION',							'解锁建造者建造避风港改良的能力。城市每有一座已解锁但未建造的专业化区域，地脉单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_HARMONISTS_4_DESCRIPTION',							'城市每有一座已解锁但未建造的专业化区域，国家公园单元格便+1该区域对应产出。拥有保护区的城市解锁“自然之耀”项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_NATUREMACH_1_DESCRIPTION',							'魅力为“迷人的”单元格+1 [ICON_Production] 生产力、+2 [ICON_Gold] 金币。无视境内地貌的魅力值减益；解锁市政“法典”后，建造者可种植森林；若区域处于魅力为“惊艳的”单元格上，则其相邻加成+100%。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_NATUREMACH_2_DESCRIPTION',							'境内所有单元格的魅力值+1，魅力为“惊艳的”单元格+2 [ICON_Production] 生产力、+4 [ICON_Gold] 金币；若区域处于魅力为“迷人的”单元格上，则其相邻加成+100%。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_NATUREMACH_3_DESCRIPTION',							'境内所有单元格的魅力值+1，[ICON_Citizen] 公民可在山脉单元格上工作。未改良的森林与雨林+3 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_NATUREMACH_4_DESCRIPTION',							'解锁“自然改造”城市项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INDUSTRY_1_DESCRIPTION',							'解锁“炼铁术”科技后可建造工业区[COLOR:ProductionDark]【注：由模组加入的特色工业区无法享受此效果】[ENDCOLOR]，允许建造“工作坊”的强力替代品：“蒸汽机”。建造工业区+100% [ICON_Production] 生产力。工业区相邻加成也提供 [ICON_Science] 科技和 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INDUSTRY_2_DESCRIPTION',							'工业区内地域加成建筑的延伸范围向外扩展3格。来自工业区建筑的 [ICON_Production] 生产力+100%。工业区相邻加成+100%。不与其他文明交战时城市+15% [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INDUSTRY_3_DESCRIPTION',							'每个工业区内建筑向城市提供4点 [ICON_Power] 电力。城市 [ICON_Power] 供电充足时，获得以下效果：通过耗电提供额外产出的建筑相应产出+4；进行城市项目+30% [ICON_Production] 生产力；工业区相邻加成+100%。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_INDUSTRY_4_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个蒸汽飞艇单位。解锁“重返过去”城市项目。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BROTHERHOOD_1_DESCRIPTION',						'首次采用该政策时 [ICON_Capital] 首都出现1个飞鸟直升机单位。+1钢铁兄弟会点数，解锁单位“钢铁兄弟会扈从”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BROTHERHOOD_2_DESCRIPTION',						'首次采用该政策时 [ICON_Capital] 首都出现1个飞鸟直升机单位。+2钢铁兄弟会点数，解锁单位“钢铁兄弟会新兵”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BROTHERHOOD_3_DESCRIPTION',						'首次采用该政策时 [ICON_Capital] 首都出现1个飞鸟直升机单位。+3钢铁兄弟会点数，解锁单位“钢铁兄弟会骑士”和“钢铁兄弟会学士”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_BROTHERHOOD_4_DESCRIPTION',						'+4钢铁兄弟会点数，解锁单位“飞鸟直升机”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_WEREWOLVES_1_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个狼人单位。允许用 [ICON_Faith] 信仰值购买狼人。这是一种行动快速且成群出击的单位，每回合能回复生命值且会随着结社的升级逐渐变强。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_WEREWOLVES_2_DESCRIPTION',							'狼人的移动力和战斗力得到永久强化。所有单位永久获得“狼血”能力，提供更大的视野范围和 [ICON_Movement] 移动力。狼人击杀敌方单位后获得额外 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_WEREWOLVES_3_DESCRIPTION',							'狼人的移动力和战斗力得到永久强化，永久获得击败单位后将其转化为狼人的能力。允许建造“月长石”，一种相邻地貌时提供更高产出的强力改良。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_WEREWOLVES_4_DESCRIPTION',							'狼人的移动力和战斗力得到永久强化，永久获得“族群领袖”能力，令2个单元格内的陆地单位+2 [ICON_Movement] 移动力且每回合能回复生命值。此卡取下后将自动销毁。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_ASSASSINS_1_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“刺客”单位，并在地图上永久显示“伊甸碎片”资源。允许建造改良“伊甸碎片抑制器”。允许建造“纪念碑”的强力替代品：“刺客分部”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_ASSASSINS_2_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“刺客”单位。允许建造刺客单位。允许建造特殊支援单位“伊甸裹尸布”。新训练的间谍获得“飞贼”升级。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_ASSASSINS_3_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“刺客”单位。允许建造特色建筑“眼”。+1间谍容量，间谍在出击行动时增加1级，间谍获得能力“情报员”。'),
		('zh_Hans_CN',	'LOC_POLICY_KOSS_ASSASSINS_4_DESCRIPTION',							'首次采用该政策时 [ICON_Capital] 首都出现1个“刺客”单位。解锁“启动全球极光装置”城市项目。+1间谍容量。'),

		('zh_Hans_CN',	'LOC_GOVT_FILTER_KING_OF_SECRET_SOCIETY',							'结社之王'),

		('zh_Hans_CN',	'LOC_PEDIA_PAGE_GOVERNOR_KNM_KING_OF_SECRET_SOCIETY_TAB_NAME',		'结社之王头衔'),
		('zh_Hans_CN',	'LOC_PEDIA_PAGE_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_1_CHAPTER_HISTORY_PARA_1',		'你的国度获得了火种，一切神秘的火种，秘密结社看似奇葩争艳，却都预备着点燃更盛大的烈焰。“我期望着，地脉筑起方尖碑，帷幕之后斟满血酒。”'),
		('zh_Hans_CN',	'LOC_PEDIA_PAGE_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_2_CHAPTER_HISTORY_PARA_1',		'书册翻开了新的一页，你的子民似乎已成功欺诈了疯狂的神秘，在刚建成的宝库前，口生獠牙者引来力量。'),
		('zh_Hans_CN',	'LOC_PEDIA_PAGE_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_3_CHAPTER_HISTORY_PARA_1',		'解构，继续解构，一切伟力已然尽展轨迹，不再需要祈祷，不再需要乞求，以自己的造物，我们便能挥洒神秘。'),
		('zh_Hans_CN',	'LOC_PEDIA_PAGE_GOVERNOR_PROMOTION_KING_OF_SECRET_SOCIETY_4_CHAPTER_HISTORY_PARA_1',		'记录终于完成，一切的力量汇集为神秘的至高书卷，从空白到盈满，文字与笔墨为窃火者们加冕。');

INSERT OR REPLACE INTO LocalizedText 
		(Language,		Tag,																Text)
VALUES	('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_STARBORNE_EMISSARIES_NAME',					'天外密使'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_STARBORNE_EMISSARIES_DESCRIPTION',			'天外密使是一个致力于指导其他文明发展的外星种族。他们专注于科学进步和工业开发。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_STARBORNE_EMISSARIES_1_DESCRIPTION',	'发现部落村庄后解锁。建造奇观时+15% [ICON_Production] 生产力。相邻奇观的学院建成时获得一个当前时代的随机 [ICON_TechBoosted] 尤里卡。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_STARBORNE_EMISSARIES_2_DESCRIPTION',	'在中世纪解锁。所有城市每2 [ICON_Citizen] 人口即可建造新区域，而非3 [ICON_Citizen] 人口。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_STARBORNE_EMISSARIES_3_DESCRIPTION',	'在工业时代解锁。允许建造强力的工业区建筑，超铀发电厂。需要消耗 [ICON_RESOURCE_JGP_ELERIUM] 超铀，一种由研究实验室生产的特色战略资源。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_STARBORNE_EMISSARIES_4_DESCRIPTION',	'在原子能时代解锁。为太空竞赛项目+20% [ICON_Production] 生产力。解锁宇航中心特色项目“出使银河”。'),
		('zh_Hans_CN',	'LOC_BUILDING_JGP_ELERIUM_POWER_PLANT_NAME',						'超铀发电厂'),
		('zh_Hans_CN',	'LOC_BUILDING_JGP_ELERIUM_POWER_PLANT_DESCRIPTION',					'天外密使专属。该工业区的 [ICON_PRODUCTION] 生产力相邻加成也提供 [ICON_SCIENCE] 科技。[NEWLINE]将任意数量的 [ICON_RESOURCE_JGP_ELERIUM] 超铀自动转换为 [ICON_Power] 电力，每回合可为周围6个单元格内的城市提供所需电力：[NEWLINE][ICON_Bullet]1点 [ICON_RESOURCE_JGP_ELERIUM] 超铀 [ICON_PowerRight] 16 [ICON_Power] Power[NEWLINE][ICON_Bullet]不会向大气层排放二氧化碳[NEWLINE]其 [ICON_Production] 生产力和 [ICON_Science] 科技加成延伸到6单元格内的所有市中心（前提是其尚未从其他的发电厂建筑获得加成）。'),
		('zh_Hans_CN',	'LOC_EMERGENCY_SCORE_JGP_ELERIUM_PLANT',							'维护超铀发电厂'),
		('zh_Hans_CN',	'LOC_PROJECT_JGP_CONVERT_TO_ELERIUM_NAME',							'转换为超铀发电'),
		('zh_Hans_CN',	'LOC_PROJECT_JGP_CONVERT_TO_ELERIUM_DESCRIPTION',					'将城市中的发电站更换为{LOC_BUILDING_JGP_ELERIUM_POWER_PLANT_NAME}.[NEWLINE][NEWLINE]{LOC_BUILDING_JGP_ELERIUM_POWER_PLANT_NAME}:[NEWLINE]{LOC_BUILDING_JGP_ELERIUM_POWER_PLANT_DESCRIPTION}'),
		('zh_Hans_CN',	'LOC_PROJECT_JGP_GALACTIC_EMBASSY_DESCRIPTION',						'天外密使专属。完成时奖励2点外交胜利点数。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_BRIGAND_COURT_NAME',							'海盗廷会'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_BRIGAND_COURT_DESCRIPTION',					'海盗廷会是一群意志坚强的海盗，他们的主要目标是积累财富——不惜任何必要的手段。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_BRIGAND_COURT_1_DESCRIPTION',			'清除蛮族营地后解锁。清除蛮族营寨后+1 [ICON_TradeRoute] 贸易路线。解锁单位“幻影旗舰”，该单位只能同时拥有一艘。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_BRIGAND_COURT_2_DESCRIPTION',			'在中世纪解锁。允许建造“灯塔”的强力替代品：亡命徒港湾。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_BRIGAND_COURT_3_DESCRIPTION',			'在工业时代解锁。海军单位获得海岸掠夺的能力。所有单位掠夺改良和区域将获得双倍收益。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_BRIGAND_COURT_4_DESCRIPTION',			'在原子能时代解锁。在地图上显示 [ICON_RESOURCE_JGP_TREASURE_TROVE] 无主财宝资源，收获后将获得大量 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_BUILDING_JGP_OUTLAW_PORT_DESCRIPTION',							'海盗廷会专属。此城生产的所有海军单位+25%战斗经验值。此城的所有海岸单元格+1 [ICON_FOOD] 食物。从建造或最后被修复开始每个时代+2 [ICON_GOLD] 金币。如此城尚无市场，则+1 [ICON_TradeRoute] 贸易路线容量。'),
		('zh_Hans_CN',	'LOC_BUILDING_JGP_OUTLAW_PORT_DESCRIPTION_XP2',						'海盗廷会专属。此城生产的所有海军单位+25%战斗经验值。此城的所有海岸单元格+1 [ICON_FOOD] 食物。从建造或最后被修复开始每个时代+2 [ICON_GOLD] 金币。如果此城与海岸相邻，则+2 [ICON_HOUSING] 住房。如此城尚无市场，则+1 [ICON_TradeRoute] 贸易路线容量。'),
		('zh_Hans_CN',	'LOC_UNIT_JGP_PHANTOM_FLAGSHIP_DESCRIPTION',						'海盗廷会特色海军单位。首次建造灯塔、造船厂和港口建筑时 [ICON_Strength] 战斗力将增加。'),
		('zh_Hans_CN',	'LOC_ABILITY_JGP_PHANTOM_FLAGSHIP_LIGHTHOUSE_STRENGTH_DESCRIPTION',	'+15 来自灯塔的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_ABILITY_JGP_PHANTOM_FLAGSHIP_SHIPYARD_STRENGTH_DESCRIPTION',	'+20 来自造船厂的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_ABILITY_JGP_PHANTOM_FLAGSHIP_SEAPORT_STRENGTH_DESCRIPTION',	'+25 来自港口的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_LIGHTHOUSE_STRENGTH_DESCRIPTION',		'+15 来自灯塔的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_SHIPYARD_STRENGTH_DESCRIPTION',		'+20 来自造船厂的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_SEAPORT_STRENGTH_DESCRIPTION',		'+25 来自港口的 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_STRENGTH_VS_BARBARIANS_DESCRIPTION',				'该单位和所有相邻海军单位：对野蛮人+5 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_EXTRA_ATTACK_AND_MOVE_DESCRIPTION',				'该单位和所有相邻海军单位：每回合+1额外攻击。攻击后可移动。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_GOLD_ON_TRADER_PILLAGE_DESCRIPTION',				'该单位和所有相邻海军单位：在海上掠夺商人+50% [ICON_GOLD] 金币。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_RANGE_AND_STRENGTH_DESCRIPTION',					'该单位和所有相邻海军单位：+1 [ICON_Range] 攻击范围。+5 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_GOLD_ON_UNIT_DEFEATED_DESCRIPTION',				'该单位和所有相邻海军单位：击杀单位可获得等同于被击杀单位 [ICON_Strength] 战斗力的 [ICON_GOLD] 金币。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_EXTRA_MOVEMENT_DESCRIPTION',						'该单位和所有相邻海军单位：+2 [ICON_Movement] 移动力。'),
		('zh_Hans_CN',	'LOC_PROMOTION_JGP_CAPTURE_UNITS_DESCRIPTION',						'该单位和所有相邻海军单位：击败敌方海军单位后可将其俘获。'),
		('zh_Hans_CN',	'LOC_RESOURCE_JGP_TREASURE_TROVE_NAME',								'无主财宝'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_STRENGTH_VS_BARBARIANS_TEXT',			'对野蛮人+5 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_EXTRA_ATTACK_TEXT',					'每回合+1额外攻击。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_MOVE_AFTER_ATTACK_TEXT',				'攻击后可移动。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_GOLD_ON_TRADER_PILLAGE_TEXT',			'在海上掠夺商人+50% [ICON_GOLD] 金币。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_EXTRA_RANGE_TEXT',					'+1 [ICON_Range] 攻击范围。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_EXTRA_STRENGTH_PREVIEW',				'+5来自相邻幻影旗舰。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_EXTRA_STRENGTH_TEXT',					'+5 [ICON_Strength] 战斗力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_GOLD_ON_UNIT_DEFEATED_TEXT',			'击杀单位可获得等同于被击杀单位 [ICON_Strength] 战斗力的 [ICON_GOLD] 金币。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_EXTRA_MOVEMENT_TEXT',					'+2 [ICON_Movement] 移动力。'),
		('zh_Hans_CN',	'LOC_MOD_JGP_PHANTOM_FLAGSHIP_CAPTURE_UNITS_TEXT',					'击败敌方海军单位后可将其俘获。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_HARMONISTS_NAME',							'调谐者'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_JGP_HARMONISTS_DESCRIPTION',						'调谐者是一个松散的组织，由与自然和谐相处的个体组成。他们厌恶蔓延的都市建筑群，青睐在严酷的荒野中求生。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_HARMONISTS_1_DESCRIPTION',				'发现自然奇观后解锁。在地图上显示“地脉”资源。城市每有一座已解锁但未建造的专业化区域，地脉单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_HARMONISTS_2_DESCRIPTION',				'在中世纪解锁。保护区和建筑+2 [ICON_Housing] 住房、+10%城市发展速度。城市每有一座已解锁但未建造的专业化区域，相邻保护区的单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_HARMONISTS_3_DESCRIPTION',				'在工业时代解锁。解锁建造者建造避风港改良的能力。城市每有一座已解锁但未建造的专业化区域，地脉单元格便+1该区域对应产出。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_JGP_HARMONISTS_4_DESCRIPTION',				'在原子能时代解锁。城市每有一座已解锁但未建造的专业化区域，国家公园单元格便+1该区域对应产出。拥有保护区的城市解锁“自然之耀”项目。'),
		('zh_Hans_CN',	'LOC_IMPROVEMENT_JGP_HAVEN_DESCRIPTION',							'可建造在任何陆地地形、地貌或资源上。如果建造在有资源或地貌的单元格上，所有相邻单元格获得+1这种资源或者地貌的每种产出类型，最高可叠加至2点。该单元格获得等同于吸引力一半数量的 [ICON_Food] 食物产出。该单元格上的战略资源和奢侈资源视为已改良。'),
		('zh_Hans_CN',	'LOC_PROJECT_JGP_HARMONISTS_GLORY_OF_NATURE_DESCRIPTION',			'提供所有类型的伟人点数。令该城市的保护区+2 [ICON_Tourism] 旅游业绩，国家公园 +10% [ICON_Tourism] 旅游业绩。'),
		('zh_Hans_CN',	'LOC_JGP_MORE_LEY_LINES',											'更多地脉'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_THB_MOONLIT_HUNT_NAME',							'月下猎杀团'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_THB_MOONLIT_HUNT_DESCRIPTION',					'月下猎杀团接纳了我们内心中野性的一面，崇拜着自然法则且喜欢成群结队猎杀敌人。他们专注于征服，扩张和信仰自己的教条。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_THB_MOONLIT_HUNT_DISCOVERY',						'你的卫兵在荒野中抓住了一只奇怪的生物——长得既像人，又像野兽。惊讶的是，在地牢中再次探望的时候，它却又变成了一个普通而粗犷的人形，并向你提供了一种途径，让你释放内心深藏的狩猎本性。虽然你的理性告诉你，快点关上牢门且永远不要再回来，但你的内心却被他的瞳孔中无形而又深邃的东西所吸引。'),
		('zh_Hans_CN',	'LOC_SECRETSOCIETY_THB_MOONLIT_HUNT_MEMBERSHIP',					'只是轻轻咬了一小口……你接受了这一恩赐，随着月光洒落在你的新长出的毛皮上，你感受到了对猎杀的兴奋，和对人类血肉的渴望。你将为你的子民传播这一恩赐，并且邀请他们加入猎杀团。在月光下，听闻嚎叫声穿透夜空，意味着猎杀时刻要来临了。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_1_NAME',					'新月'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_1_DESCRIPTION',			'发现自然奇观或部落村庄后解锁。允许购买狼人，一种行动更快且成群出击的单位，每回合能回复生命值且会随着结社的升级逐渐变强。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_2_NAME',					'弦月'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_2_DESCRIPTION',			'所有单位获得“狼血”能力，提供更大的视野范围和 [ICON_Movement] 移动力。狼人击杀敌方单位后获得额外 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_3_NAME',					'满月'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_3_DESCRIPTION',			'允许建造“月长石”，一种相邻地貌时提供更高产出的强力改良。狼人在击败单位后能将其转化为狼人。'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_4_NAME',					'血月'),
		('zh_Hans_CN',	'LOC_GOVERNOR_PROMOTION_THB_MOONLIT_HUNT_4_DESCRIPTION',			'狼人获得“族群领袖”升级，令2个单元格内的陆地单位+2 [ICON_Movement] 移动力且每回合能回复生命值。'),
		('zh_Hans_CN',	'LOC_ABILITY_THB_WEREWOLF_HEALING_DESCRIPTION',						'每回合能回复生命值'),
		('zh_Hans_CN',	'LOC_ABILITY_THB_WEREWOLF_PACK_COMBAT_DESCRIPTION',					'从附近的狼人单位获得 [ICON_Strength] 战斗力增益'),
		('zh_Hans_CN',	'LOC_THB_WOLF_BLOOD_DESCRIPTION',									'狼血为单位提供+1 [ICON_Movement] 移动力和+1视野'),
		('zh_Hans_CN',	'LOC_THB_WOLF_FAITH_KILL_DESCRIPTION',								'击杀单位后获得等同于被击杀单位 [ICON_Strength] 战斗力20%的 [ICON_Faith] 信仰值。'),
		('zh_Hans_CN',	'LOC_THB_WOLF_CONVERT_KILL_DESCRIPTION',							'将战败单位转化为狼人。'),
		('zh_Hans_CN',	'LOC_THB_WILD_PACK_DESCRIPTION',									'作为族群的一员+2 [ICON_Movement] 移动力且每回合能回复生命值。'),
		('zh_Hans_CN',	'LOC_THB_WEREWOLF_PACK_LEADER_DESCRIPTION',							'作为族群领袖，令附近的单位+2 [ICON_Movement] 移动力且能额外回复生命值。'),
		('zh_Hans_CN',	'LOC_ABILITY_THB_WEREWOLF_PACK_COMBAT_STRING',						'+3 [ICON_Strength] 战斗力来自相邻狼人'),
		('zh_Hans_CN',	'LOC_IMPROVEMENT_THB_LUNAR_CIRCLE_NAME',							'月长石'),
		('zh_Hans_CN',	'LOC_IMPROVEMENT_THB_LUNAR_CIRCLE_DESCRIPTION',						'提供+1 [ICON_Food] 食物和等同于单元格魅力50%的 [ICON_Faith] 信仰值。每相邻2个同类型地貌额外提供+1 [ICON_Faith] 信仰、 [ICON_Science] 科技值和 [ICON_Culture] 文化值。根据相邻地貌（包括自然奇观）提供额外产出加成。必须建造在魅力值达到0或更高的空单元格上。每个城市只能修建1座。'),
		('zh_Hans_CN',	'LOC_UNIT_THB_WEREWOLF_NAME',										'狼人'),
		('zh_Hans_CN',	'LOC_UNIT_THB_WEREWOLF_DESCRIPTION',								'月下猎杀团专属，行动迅速的强力单位。每回合回复15生命值，相邻狼人时+3 [ICON_Strength] 战斗力。随着结社升级获得移动力、攻击力和其他加成。');
